import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { DarkModeProvider } from "./components/DarkModeProvider/DarkModeProvider";
import Sidebar from "./components/Sidebar/Sidebar";
import TopNavbar from "./components/TopNavbar/TopNavbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title:
    "Girona Film Festival - Movie administration and download your certificate",
  description: "Generated by Girona Film Festival",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-white transition-colors duration-300`}
      >
        <DarkModeProvider>
          <div className="min-h-screen flex flex-col">
            <TopNavbar />

            <div className="flex flex-1">
              {/* Sidebar will render differently per screen size */}
              <Sidebar />

              {/* Main content area */}
              <div className="flex-1">
                {children}
              </div>
            </div>
          </div>

          <Toaster 
            toastOptions={{
              className: 'bg-white dark:bg-gray-900 text-gray-900 dark:text-white',
            }}
          />
        </DarkModeProvider>
      </body>
    </html>
  );
}
